-- Generated by Oracle SQL Developer Data Modeler 24.3.1.351.0831
--   at:        2026-05-05 19:20:50 EEST
--   site:      Oracle Database 11g
--   type:      Oracle Database 11g



-- predefined type, no DDL - MDSYS.SDO_GEOMETRY

-- predefined type, no DDL - XMLTYPE

CREATE TABLE adresa 
    ( 
     cod_adresa NUMBER (7)  NOT NULL , 
     strada     VARCHAR2 (100)  NOT NULL , 
     oras       VARCHAR2 (50)  NOT NULL , 
     judet      VARCHAR2 (50)  NOT NULL , 
     zip_code   NUMBER (10)  NOT NULL 
    ) 
;

ALTER TABLE adresa 
    ADD CONSTRAINT adresa_zip_code_ck 
    CHECK (zip_code REGEXP '^[0-9]+$') 
;

ALTER TABLE adresa 
    ADD CONSTRAINT adresa_PK PRIMARY KEY ( cod_adresa ) ;

ALTER TABLE adresa 
    ADD CONSTRAINT adresa_cod_adresa_uk UNIQUE ( cod_adresa ) ;

CREATE TABLE articole_vestimentare 
    ( 
     cod_articol NUMBER (10)  NOT NULL , 
     pret        NUMBER (6,3)  NOT NULL , 
     marime      CHAR (5)  NOT NULL , 
     firma       CHAR (15)  NOT NULL , 
     tip         CHAR (20)  NOT NULL , 
     stoc        NUMBER (5)  NOT NULL 
    ) 
;

ALTER TABLE articole_vestimentare 
    ADD CONSTRAINT articole_vestimentare_pret_ck 
    CHECK (pret > 0) 
;

ALTER TABLE articole_vestimentare 
    ADD CONSTRAINT articole_vestimentare_tip_ck 
    CHECK (tip IN ('hanorac', 'incaltaminte', 'tricou')) 
;

ALTER TABLE articole_vestimentare 
    ADD CONSTRAINT ar_ve_marime_ck 
    CHECK (marime IN ('L', 'M', 'S', 'XL', 'XXL'))
;


ALTER TABLE articole_vestimentare 
    ADD CONSTRAINT ar_ve_stoc_ck 
    CHECK (stoc >= 0)
;
ALTER TABLE articole_vestimentare 
    ADD CONSTRAINT articole_vestimentare_PK PRIMARY KEY ( cod_articol ) ;

ALTER TABLE articole_vestimentare 
    ADD CONSTRAINT ar_ve_cod_articol_uk UNIQUE ( cod_articol ) ;

CREATE TABLE Clienti 
    ( 
     cod_client NUMBER (10)  NOT NULL , 
     nume       CHAR (30)  NOT NULL , 
     prenume    CHAR (30)  NOT NULL 
    ) 
;

ALTER TABLE Clienti 
    ADD CONSTRAINT Clienti_PK PRIMARY KEY ( cod_client ) ;

CREATE TABLE clienti_ar_ve_fk 
    ( 
     Clienti_cod_client NUMBER (10)  NOT NULL , 
     ar_ve_cod_articol  NUMBER (10)  NOT NULL 
    ) 
;

ALTER TABLE clienti_ar_ve_fk 
    ADD CONSTRAINT Clienti_ar_ve_fk_PK PRIMARY KEY ( Clienti_cod_client, ar_ve_cod_articol ) ;

CREATE TABLE comanda_articole 
    ( 
     cantitate   NUMBER (5)  NOT NULL , 
     pret_unitar NUMBER (8,2)  NOT NULL , 
     cod_client  NUMBER (10)  NOT NULL , 
     cod_comanda NUMBER (10)  NOT NULL , 
     cod_articol NUMBER (10)  NOT NULL 
    ) 
;

CREATE TABLE conturi 
    ( 
     email         VARCHAR2 (40)  NOT NULL , 
     parola        VARCHAR2 (50)  NOT NULL , 
     numar_telefon VARCHAR2 (12)  NOT NULL , 
     cod_client    NUMBER (10)  NOT NULL 
    ) 
;

ALTER TABLE conturi 
    ADD 
    CHECK (regexp_like(email, '[a-z0-9._%-]+@[a-z0-9._%-]+\.[a-z]{2,4}')) 
;

ALTER TABLE conturi 
    ADD 
    CHECK (numar_telefon REGEXP '^[0-9]+$') 
;
CREATE UNIQUE INDEX conturi__IDX ON conturi 
    ( 
     cod_client ASC 
    ) 
;

ALTER TABLE conturi 
    ADD CONSTRAINT conturi_email_uk UNIQUE ( email ) ;

ALTER TABLE conturi 
    ADD CONSTRAINT conturi_numar_telefon_uk UNIQUE ( numar_telefon ) ;

CREATE TABLE detalii_comanda 
    ( 
     cod_comanda       NUMBER (10)  NOT NULL , 
     data_plasare      DATE  NOT NULL , 
     modalitate_plata  VARCHAR2 (10)  NOT NULL , 
     cod_client        NUMBER (10)  NOT NULL , 
     status_comanda    VARCHAR2 (20)  NOT NULL , 
     adresa_cod_adresa NUMBER (7)  NOT NULL 
    ) 
;

ALTER TABLE detalii_comanda 
    ADD CONSTRAINT det_com_mod_plata_ck 
    CHECK (modalitate_plata IN ('numerar', 'card'))
;


ALTER TABLE detalii_comanda 
    ADD CONSTRAINT det_com_status_ck 
    CHECK (status_comanda IN ('plasata', 'preluata', 'livrata', 'anulata'))
;
ALTER TABLE detalii_comanda 
    ADD CONSTRAINT detalii_comanda_PK PRIMARY KEY ( cod_client, cod_comanda ) ;

CREATE TABLE detalii_curier 
    ( 
     cod_curier    NUMBER (10)  NOT NULL , 
     data_ridicare DATE  NOT NULL , 
     data_predare  DATE  NOT NULL , 
     cod_client    NUMBER (10)  NOT NULL , 
     cod_comanda   NUMBER (10)  NOT NULL 
    ) 
;

ALTER TABLE detalii_curier 
    ADD CONSTRAINT detalii_curier_PK PRIMARY KEY ( cod_curier, cod_client, cod_comanda ) ;

ALTER TABLE detalii_comanda 
    ADD CONSTRAINT adresa_detalii_comanda FOREIGN KEY 
    ( 
     adresa_cod_adresa
    ) 
    REFERENCES adresa 
    ( 
     cod_adresa
    ) 
;

ALTER TABLE comanda_articole 
    ADD CONSTRAINT articole_comanda_articole FOREIGN KEY 
    ( 
     cod_articol
    ) 
    REFERENCES articole_vestimentare 
    ( 
     cod_articol
    ) 
;

ALTER TABLE clienti_ar_ve_fk 
    ADD CONSTRAINT Clienti_ar_ve_fk_ar_ve_FK FOREIGN KEY 
    ( 
     ar_ve_cod_articol
    ) 
    REFERENCES articole_vestimentare 
    ( 
     cod_articol
    ) 
;

ALTER TABLE clienti_ar_ve_fk 
    ADD CONSTRAINT Clienti_ar_ve_fk_Cli_FK FOREIGN KEY 
    ( 
     Clienti_cod_client
    ) 
    REFERENCES Clienti 
    ( 
     cod_client
    ) 
;

ALTER TABLE conturi 
    ADD CONSTRAINT Clienti_conturi_fk FOREIGN KEY 
    ( 
     cod_client
    ) 
    REFERENCES Clienti 
    ( 
     cod_client
    ) 
;

ALTER TABLE detalii_comanda 
    ADD CONSTRAINT Clienti_detalii_comanda_fk FOREIGN KEY 
    ( 
     cod_client
    ) 
    REFERENCES Clienti 
    ( 
     cod_client
    ) 
;

ALTER TABLE comanda_articole 
    ADD CONSTRAINT det_com_com_art_fk FOREIGN KEY 
    ( 
     cod_client,
     cod_comanda
    ) 
    REFERENCES detalii_comanda 
    ( 
     cod_client,
     cod_comanda
    ) 
;

ALTER TABLE detalii_curier 
    ADD CONSTRAINT det_com_curier_fk FOREIGN KEY 
    ( 
     cod_client,
     cod_comanda
    ) 
    REFERENCES detalii_comanda 
    ( 
     cod_client,
     cod_comanda
    ) 
;

CREATE SEQUENCE adresa_cod_adresa_SEQ 
START WITH 1 
    INCREMENT BY 8 
    NOCACHE 
    ORDER ;

CREATE OR REPLACE TRIGGER adresa_cod_adresa_TRG 
BEFORE INSERT ON adresa 
FOR EACH ROW 
WHEN (NEW.cod_adresa IS NULL) 
BEGIN 
    :NEW.cod_adresa := adresa_cod_adresa_SEQ.NEXTVAL; 
END;
/

CREATE SEQUENCE articole_vestimentare_cod_arti 
START WITH 1 
    INCREMENT BY 7 
    NOCACHE 
    ORDER ;

CREATE OR REPLACE TRIGGER articole_vestimentare_cod_arti 
BEFORE INSERT ON articole_vestimentare 
FOR EACH ROW 
WHEN (NEW.cod_articol IS NULL) 
BEGIN 
    :NEW.cod_articol := articole_vestimentare_cod_arti.NEXTVAL; 
END;
/

CREATE SEQUENCE Clienti_cod_client_SEQ 
START WITH 1 
    NOCACHE 
    ORDER ;

CREATE OR REPLACE TRIGGER Clienti_cod_client_TRG 
BEFORE INSERT ON Clienti 
FOR EACH ROW 
WHEN (NEW.cod_client IS NULL) 
BEGIN 
    :NEW.cod_client := Clienti_cod_client_SEQ.NEXTVAL; 
END;
/

CREATE SEQUENCE clienti_ar_ve_fk_Clienti_cod_c 
START WITH 1 
    INCREMENT BY 2 
    NOCACHE 
    ORDER ;

CREATE OR REPLACE TRIGGER clienti_ar_ve_fk_Clienti_cod_c 
BEFORE INSERT ON clienti_ar_ve_fk 
FOR EACH ROW 
WHEN (NEW.Clienti_cod_client IS NULL) 
BEGIN 
    :NEW.Clienti_cod_client := clienti_ar_ve_fk_Clienti_cod_c.NEXTVAL; 
END;
/

CREATE SEQUENCE clienti_ar_ve_fk_ar_ve_cod_art 
START WITH 1 
    INCREMENT BY 3 
    NOCACHE 
    ORDER ;

CREATE OR REPLACE TRIGGER clienti_ar_ve_fk_ar_ve_cod_art 
BEFORE INSERT ON clienti_ar_ve_fk 
FOR EACH ROW 
WHEN (NEW.ar_ve_cod_articol IS NULL) 
BEGIN 
    :NEW.ar_ve_cod_articol := clienti_ar_ve_fk_ar_ve_cod_art.NEXTVAL; 
END;
/

CREATE SEQUENCE detalii_comanda_cod_comanda 
START WITH 1 
    INCREMENT BY 5 
    NOCACHE 
    ORDER ;

CREATE OR REPLACE TRIGGER detalii_comanda_cod_comanda 
BEFORE INSERT ON detalii_comanda 
FOR EACH ROW 
WHEN (NEW.cod_comanda IS NULL) 
BEGIN 
    :NEW.cod_comanda := detalii_comanda_cod_comanda.NEXTVAL; 
END;
/

CREATE SEQUENCE detalii_comanda_cod_client_SEQ 
START WITH 1 
    NOCACHE 
    ORDER ;

CREATE OR REPLACE TRIGGER detalii_comanda_cod_client_TRG 
BEFORE INSERT ON detalii_comanda 
FOR EACH ROW 
WHEN (NEW.cod_client IS NULL) 
BEGIN 
    :NEW.cod_client := detalii_comanda_cod_client_SEQ.NEXTVAL; 
END;
/

CREATE SEQUENCE detalii_curier_cod_curier_SEQ 
START WITH 1 
    INCREMENT BY 6 
    NOCACHE 
    ORDER ;

CREATE OR REPLACE TRIGGER detalii_curier_cod_curier_TRG 
BEFORE INSERT ON detalii_curier 
FOR EACH ROW 
WHEN (NEW.cod_curier IS NULL) 
BEGIN 
    :NEW.cod_curier := detalii_curier_cod_curier_SEQ.NEXTVAL; 
END;
/

CREATE SEQUENCE detalii_curier_cod_client_SEQ 
START WITH 1 
    NOCACHE 
    ORDER ;

CREATE OR REPLACE TRIGGER detalii_curier_cod_client_TRG 
BEFORE INSERT ON detalii_curier 
FOR EACH ROW 
WHEN (NEW.cod_client IS NULL) 
BEGIN 
    :NEW.cod_client := detalii_curier_cod_client_SEQ.NEXTVAL; 
END;
/

CREATE SEQUENCE detalii_curier_cod_comanda_SEQ 
START WITH 1 
    INCREMENT BY 5 
    NOCACHE 
    ORDER ;

CREATE OR REPLACE TRIGGER detalii_curier_cod_comanda_TRG 
BEFORE INSERT ON detalii_curier 
FOR EACH ROW 
WHEN (NEW.cod_comanda IS NULL) 
BEGIN 
    :NEW.cod_comanda := detalii_curier_cod_comanda_SEQ.NEXTVAL; 
END;
/



-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                             8
-- CREATE INDEX                             1
-- ALTER TABLE                             27
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                          10
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                         10
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
