    -- Generated by Oracle SQL Developer Data Modeler 24.3.0.240.1210
    --   at:        2024-12-11 19:19:10 EET
    --   site:      Oracle Database 11g
    --   type:      Oracle Database 11g



    -- predefined type, no DDL - MDSYS.SDO_GEOMETRY

    -- predefined type, no DDL - XMLTYPE

    CREATE TABLE adresa (
        cod_adresa NUMBER(7) NOT NULL,
        strada     VARCHAR2(100) NOT NULL,
        oras       VARCHAR2(50) NOT NULL,
        judet      VARCHAR2(50) NOT NULL,
        zip_code   NUMBER(10) NOT NULL
    )
    LOGGING;

    ALTER TABLE adresa ADD constraint adresa_zip_code_ck check (REGEXP_LIKE (zip_code, '^[0-9]+$' ));

    ALTER TABLE adresa ADD CONSTRAINT adresa_pk PRIMARY KEY ( cod_adresa );

    ALTER TABLE adresa ADD CONSTRAINT adresa_cod_adresa_uk UNIQUE ( cod_adresa );

    CREATE TABLE articole_vestimentare (
        cod_articol NUMBER(10) NOT NULL,
        pret        NUMBER(6, 3) NOT NULL,
        marime      CHAR(5) NOT NULL,
        firma       CHAR(15) NOT NULL,
        tip         CHAR(20) NOT NULL
    )
    LOGGING;

    ALTER TABLE articole_vestimentare ADD CONSTRAINT articole_vestimentare_pret_ck CHECK ( pret > 0 );

    ALTER TABLE articole_vestimentare ADD CONSTRAINT ar_ve_marime_ck CHECK ( marime IN ( 'L', 'M', 'S', 'XL', 'XXL' ) );

    ALTER TABLE articole_vestimentare ADD CONSTRAINT articole_vestimentare_tip_ck CHECK ( tip IN ( 'hanorac', 'incaltaminte', 'tricou' ) );

    ALTER TABLE articole_vestimentare ADD CONSTRAINT articole_vestimentare_pk PRIMARY KEY ( cod_articol );

    ALTER TABLE articole_vestimentare ADD CONSTRAINT ar_ve_cod_articol_uk UNIQUE ( cod_articol );

    CREATE TABLE clienti (
        cod_client NUMBER(10) NOT NULL,
        nume       CHAR(30) NOT NULL,
        prenume    CHAR(30) NOT NULL
    )
    LOGGING;

    ALTER TABLE clienti ADD CONSTRAINT clienti_pk PRIMARY KEY ( cod_client );

    CREATE TABLE clienti_ar_ve_fk (clienti_cod_client NUMBER(10) NOT NULL, ar_ve_cod_articol  NUMBER(10) NOT NULL) LOGGING;

    ALTER TABLE clienti_ar_ve_fk ADD CONSTRAINT clienti_ar_ve_fk_pk PRIMARY KEY ( clienti_cod_client, ar_ve_cod_articol );

    CREATE TABLE conturi (
        email         VARCHAR2(40) NOT NULL,
        parola        VARCHAR2(50) NOT NULL,
        numar_telefon VARCHAR2(12) NOT NULL,
        cod_client    NUMBER(10) NOT NULL
    )
    LOGGING;

    ALTER TABLE conturi ADD CHECK ( REGEXP_LIKE ( email, '[a-z0-9._%-]+@[a-z0-9._%-]+\.[a-z]{2,4}' ) );

    ALTER TABLE conturi ADD check (REGEXP_LIKE (numar_telefon, '^[0-9]+$')) ;

    CREATE UNIQUE INDEX conturi__idx ON conturi ( cod_client ASC ) LOGGING;

    ALTER TABLE conturi ADD CONSTRAINT conturi_email_uk UNIQUE ( email );

    ALTER TABLE conturi ADD CONSTRAINT conturi_numar_telefon_uk UNIQUE ( numar_telefon );

    CREATE TABLE detalii_comanda (
        cod_comanda      NUMBER(10) NOT NULL,
        data_plasare     DATE NOT NULL,
        modalitate_plata VARCHAR2(10) NOT NULL,
        cod_client       NUMBER(10) NOT NULL
    )
    LOGGING;

    ALTER TABLE detalii_comanda ADD CONSTRAINT detalii_comanda_mod_plata_ck CHECK ( modalitate_plata IN ( 'numerar', 'card' ) );

    ALTER TABLE detalii_comanda ADD CONSTRAINT detalii_comanda_pk PRIMARY KEY ( cod_client, cod_comanda );

    CREATE TABLE detalii_curier (
        cod_curier    NUMBER(10) NOT NULL,
        data_ridicare DATE NOT NULL,
        data_predare  DATE NOT NULL,
        cod_client    NUMBER(10) NOT NULL,
        cod_comanda   NUMBER(10) NOT NULL
    )
    LOGGING;

    ALTER TABLE detalii_curier ADD CONSTRAINT detalii_curier_pk PRIMARY KEY ( cod_curier, cod_client, cod_comanda );

    ALTER TABLE clienti_ar_ve_fk ADD CONSTRAINT clienti_ar_ve_fk_ar_ve_fk FOREIGN KEY ( ar_ve_cod_articol ) REFERENCES articole_vestimentare ( cod_articol ) NOT DEFERRABLE;

    ALTER TABLE clienti_ar_ve_fk ADD CONSTRAINT clienti_ar_ve_fk_cli_fk FOREIGN KEY ( clienti_cod_client ) REFERENCES clienti ( cod_client ) NOT DEFERRABLE;

    ALTER TABLE conturi ADD CONSTRAINT clienti_conturi_fk FOREIGN KEY ( cod_client ) REFERENCES clienti ( cod_client ) NOT DEFERRABLE;

    ALTER TABLE detalii_comanda ADD CONSTRAINT clienti_detalii_comanda_fk FOREIGN KEY ( cod_client ) REFERENCES clienti ( cod_client ) NOT DEFERRABLE;

    ALTER TABLE detalii_curier ADD CONSTRAINT detalii_com_detalii_cur_fk FOREIGN KEY ( cod_client, cod_comanda ) REFERENCES detalii_comanda ( cod_client, cod_comanda ) NOT DEFERRABLE;

    CREATE OR REPLACE TRIGGER Trg_detalii_comanda_data_plasare 
        BEFORE INSERT OR UPDATE ON detalii_comanda 
        FOR EACH ROW 
    BEGIN
    IF( :new.data_plasare <= SYSDATE )
    THEN
    RAISE_APPLICATION_ERROR( -20001,
    'Data invalida: ' || TO_CHAR( :new.data_plasare, 'DD.MM.YYYY HH24:MI:SS' ) || ' trebuie sa fie mai mare decat data curenta.' );
    END IF;
    END; 
    /

    CREATE OR REPLACE TRIGGER Trg_detalii_curier_data_predare 
        BEFORE INSERT OR UPDATE ON detalii_curier 
        FOR EACH ROW 
    BEGIN
    IF( :new.data_predare <= SYSDATE )
    THEN
    RAISE_APPLICATION_ERROR( -20001,
    'Data invalida: ' || TO_CHAR( :new.data_predare, 'DD.MM.YYYY HH24:MI:SS' ) || ' trebuie sa fie mai mare decat data curenta.' );
    END IF;
    END; 
    /

    CREATE OR REPLACE TRIGGER Trg_detalii_curier_data_ridicare 
        BEFORE INSERT OR UPDATE ON detalii_curier 
        FOR EACH ROW 
    BEGIN
    IF( :new.data_ridicare <= SYSDATE )
    THEN
    RAISE_APPLICATION_ERROR( -20001,
    'Data invalida: ' || TO_CHAR( :new.data_ridicare, 'DD.MM.YYYY HH24:MI:SS' ) || ' trebuie sa fie mai mare decat data curenta.' );
    END IF;
    END; 
    /

    CREATE SEQUENCE adresa_cod_adresa_seq START WITH 1 INCREMENT BY 8 NOCACHE ORDER;

    CREATE OR REPLACE TRIGGER adresa_cod_adresa_trg BEFORE
        INSERT ON adresa
        FOR EACH ROW
        WHEN ( new.cod_adresa IS NULL )
    BEGIN
        :new.cod_adresa := adresa_cod_adresa_seq.nextval;
    END;
    /

    CREATE SEQUENCE articole_vestimentare_cod_arti START WITH 1 INCREMENT BY 7 NOCACHE ORDER;

    CREATE OR REPLACE TRIGGER articole_vestimentare_cod_arti BEFORE
        INSERT ON articole_vestimentare
        FOR EACH ROW
        WHEN ( new.cod_articol IS NULL )
    BEGIN
        :new.cod_articol := articole_vestimentare_cod_arti.nextval;
    END;
    /

    CREATE SEQUENCE clienti_cod_client_seq START WITH 1 NOCACHE ORDER;

    CREATE OR REPLACE TRIGGER clienti_cod_client_trg BEFORE
        INSERT ON clienti
        FOR EACH ROW
        WHEN ( new.cod_client IS NULL )
    BEGIN
        :new.cod_client := clienti_cod_client_seq.nextval;
    END;
    /

    CREATE SEQUENCE clienti_ar_ve_fk_clienti_cod_c START WITH 1 INCREMENT BY 2 NOCACHE ORDER;

    CREATE OR REPLACE TRIGGER clienti_ar_ve_fk_clienti_cod_c BEFORE
        INSERT ON clienti_ar_ve_fk
        FOR EACH ROW
        WHEN ( new.clienti_cod_client IS NULL )
    BEGIN
        :new.clienti_cod_client := clienti_ar_ve_fk_clienti_cod_c.nextval;
    END;
    /

    CREATE SEQUENCE clienti_ar_ve_fk_ar_ve_cod_art START WITH 1 INCREMENT BY 3 NOCACHE ORDER;

    CREATE OR REPLACE TRIGGER clienti_ar_ve_fk_ar_ve_cod_art BEFORE
        INSERT ON clienti_ar_ve_fk
        FOR EACH ROW
        WHEN ( new.ar_ve_cod_articol IS NULL )
    BEGIN
        :new.ar_ve_cod_articol := clienti_ar_ve_fk_ar_ve_cod_art.nextval;
    END;
    /

    CREATE SEQUENCE detalii_comanda_cod_comanda START WITH 1 INCREMENT BY 5 NOCACHE ORDER;

    CREATE OR REPLACE TRIGGER detalii_comanda_cod_comanda BEFORE
        INSERT ON detalii_comanda
        FOR EACH ROW
        WHEN ( new.cod_comanda IS NULL )
    BEGIN
        :new.cod_comanda := detalii_comanda_cod_comanda.nextval;
    END;
    /

    CREATE SEQUENCE detalii_comanda_cod_client_seq START WITH 1 NOCACHE ORDER;

    CREATE OR REPLACE TRIGGER detalii_comanda_cod_client_trg BEFORE
        INSERT ON detalii_comanda
        FOR EACH ROW
        WHEN ( new.cod_client IS NULL )
    BEGIN
        :new.cod_client := detalii_comanda_cod_client_seq.nextval;
    END;
    /

    CREATE SEQUENCE detalii_curier_cod_curier_seq START WITH 1 INCREMENT BY 6 NOCACHE ORDER;

    CREATE OR REPLACE TRIGGER detalii_curier_cod_curier_trg BEFORE
        INSERT ON detalii_curier
        FOR EACH ROW
        WHEN ( new.cod_curier IS NULL )
    BEGIN
        :new.cod_curier := detalii_curier_cod_curier_seq.nextval;
    END;
    /

    CREATE SEQUENCE detalii_curier_cod_client_seq START WITH 1 NOCACHE ORDER;

    CREATE OR REPLACE TRIGGER detalii_curier_cod_client_trg BEFORE
        INSERT ON detalii_curier
        FOR EACH ROW
        WHEN ( new.cod_client IS NULL )
    BEGIN
        :new.cod_client := detalii_curier_cod_client_seq.nextval;
    END;
    /

    CREATE SEQUENCE detalii_curier_cod_comanda_seq START WITH 1 INCREMENT BY 5 NOCACHE ORDER;

    CREATE OR REPLACE TRIGGER detalii_curier_cod_comanda_trg BEFORE
        INSERT ON detalii_curier
        FOR EACH ROW
        WHEN ( new.cod_comanda IS NULL )
    BEGIN
        :new.cod_comanda := detalii_curier_cod_comanda_seq.nextval;
    END;
    /



    -- Oracle SQL Developer Data Modeler Summary Report: 
    -- 
    -- CREATE TABLE                             7
    -- CREATE INDEX                             1
    -- ALTER TABLE                             22
    -- CREATE VIEW                              0
    -- ALTER VIEW                               0
    -- CREATE PACKAGE                           0
    -- CREATE PACKAGE BODY                      0
    -- CREATE PROCEDURE                         0
    -- CREATE FUNCTION                          0
    -- CREATE TRIGGER                          13
    -- ALTER TRIGGER                            0
    -- CREATE COLLECTION TYPE                   0
    -- CREATE STRUCTURED TYPE                   0
    -- CREATE STRUCTURED TYPE BODY              0
    -- CREATE CLUSTER                           0
    -- CREATE CONTEXT                           0
    -- CREATE DATABASE                          0
    -- CREATE DIMENSION                         0
    -- CREATE DIRECTORY                         0
    -- CREATE DISK GROUP                        0
    -- CREATE ROLE                              0
    -- CREATE ROLLBACK SEGMENT                  0
    -- CREATE SEQUENCE                         10
    -- CREATE MATERIALIZED VIEW                 0
    -- CREATE MATERIALIZED VIEW LOG             0
    -- CREATE SYNONYM                           0
    -- CREATE TABLESPACE                        0
    -- CREATE USER                              0
    -- 
    -- DROP TABLESPACE                          0
    -- DROP DATABASE                            0
    -- 
    -- REDACTION POLICY                         0
    -- 
    -- ORDS DROP SCHEMA                         0
    -- ORDS ENABLE SCHEMA                       0
    -- ORDS ENABLE OBJECT                       0
    -- 
    -- ERRORS                                   0
    -- WARNINGS                                 0
